-- AlterTable
ALTER TABLE "products" ALTER COLUMN "unit_value" SET DEFAULT 1,
ALTER COLUMN "unit_value" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "original_unit_value" SET DATA TYPE DOUBLE PRECISION;
